# Generated by Django 4.1.4 on 2022-12-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_numer', models.IntegerField(verbose_name='Numéro de dossier')),
                ('last_update', models.DateField(verbose_name='Date de mise à jour')),
                ('lecture_date', models.DateField(verbose_name='Date de lecture')),
                ('lawyer', models.CharField(max_length=30, verbose_name='Avocat requérant')),
                ('decision_type', models.CharField(max_length=100, verbose_name='Type de décision')),
                ('appeal_type', models.CharField(max_length=100, verbose_name='Type de recours')),
                ('publication_code', models.CharField(max_length=20, verbose_name='Code publication')),
                ('solution', models.CharField(blank=True, default='', max_length=100, verbose_name='Solution')),
                ('text', models.CharField(max_length=100000, verbose_name='Texte intégral')),
            ],
        ),
        migrations.CreateModel(
            name='LegalBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_code', models.CharField(choices=[('CAA', 'Cours Administrative Appel'), ('CE', 'Conseil Etat'), ('TA', 'Traibunal Administratif')], max_length=20, verbose_name='Code de la juridiction')),
                ('legal_name', models.CharField(max_length=100, verbose_name='Nom de la juridiction')),
            ],
        ),
    ]
