# Generated by Django 4.1.4 on 2022-12-27 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decision',
            old_name='file_numer',
            new_name='file_nubmer',
        ),
        migrations.AddField(
            model_name='decision',
            name='legal_body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datasearch.legalbody'),
        ),
    ]
