# Generated by Django 4.1.4 on 2022-12-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasearch', '0002_rename_file_numer_decision_file_nubmer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decision',
            old_name='file_nubmer',
            new_name='file_number',
        ),
    ]
