# Generated by Django 4.1.4 on 2022-12-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasearch', '0003_rename_file_nubmer_decision_file_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalbody',
            name='legal_type',
            field=models.CharField(choices=[('CAA', 'Cours Administrative Appel'), ('CE', 'Conseil Etat'), ('TA', 'Tribunal Administratif')], max_length=20, null=True, verbose_name='Type de juridiction'),
        ),
        migrations.AlterField(
            model_name='legalbody',
            name='legal_code',
            field=models.CharField(max_length=20, verbose_name='Code de la juridiction'),
        ),
    ]
