# Generated by Django 4.1.4 on 2022-12-27 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datasearch", "0004_legalbody_legal_type_alter_legalbody_legal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="hearing_date",
            field=models.DateField(null=True, verbose_name="Date d'audience"),
        ),
        migrations.AddField(
            model_name="decision",
            name="jugement_format",
            field=models.CharField(
                default="", max_length=100, verbose_name="Formation de jugement"
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="role_number",
            field=models.IntegerField(null=True, verbose_name="Numéro de rôle"),
        ),
        migrations.AlterField(
            model_name="decision",
            name="appeal_type",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Type de recours"
            ),
        ),
        migrations.AlterField(
            model_name="decision",
            name="lawyer",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Avocat requérant"
            ),
        ),
        migrations.AlterField(
            model_name="decision",
            name="legal_body",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="datasearch.legalbody",
                verbose_name="Instance judiciaire",
            ),
        ),
    ]
